services:
  - type: web
    name: lifeweeks-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        value: 7784577846:AAGOSVUBf6J33PFSZo9ApK8NGSS4XU0Cv1w